---
abstract: 'Memory mapping made simple and safe.'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  IO::Handle: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3607'
keywords:
  - mmap
  - 'memory mapping'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Map
provides:
  File::Map:
    file: lib/File/Map.pm
    version: 0.32
requires:
  Const::Fast: 0
  Sub::Exporter: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Map
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/file-map/tree
version: 0.32
