---
name: File-Map
version: 0.16
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Memory mapping made simple and safe.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-Map
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/file-map/tree
configure_requires:
  Module::Build: 0
requires:
  Readonly: 1.03
  perl: 5.007003
build_requires:
  ExtUtils::CBuilder: 0
  IO::Handle: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  Time::HiRes: 0
  threads: 0
recommends:
  Readonly::XS: 0
provides:
  File::Map:
    file: lib/File/Map.pm
    version: 0.16
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - mmap
  - memory mapping
